stages:
  - test
  - build
  - publish

variables:
  DOCKER_BUILDKIT: "1"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
  GITHUB_MIRROR_REPO: "crusoecloud/crusoe-watch-agent"

include:
  - local: ci/log-collector.gitlab-ci.yml
  - local: ci/config-reloader.gitlab-ci.yml
  - local: ci/monitoring-token.gitlab-ci.yml
  - local: ci/helm-package.gitlab-ci.yml
  - local: ci/semver-tag.gitlab-ci.yml

# Runs if we don't change files in the submodules to ensure that a pipeline is always created.
# Attempts to track files that don't have an associated job.
no_op_pipeline_stub:
  needs: []

  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      changes:
        - .gitlab/**/*
        - runbook/**/*
        - scripts/**/*
        - README.md
        - .gitlab-ci.yml

  script: |
    echo 'job that will run if we do not change files in the submodules to ensure that a pipeline is always created'