.semver-tag-base:
  stage: publish
  image: alpine:3.19
  before_script:
    - apk add --no-cache git

semver-tag:config-reloader:
  extends: .semver-tag-base
  script:
    - |
      VERSION_FILE="k8s/vector-config-reloader/VERSION"

      if git diff --name-only HEAD~1 HEAD | grep -q "^${VERSION_FILE}"; then
        VERSION=$(tr -d ' \n' < ${VERSION_FILE})
        TAG="v${VERSION}"

        if git rev-parse "$TAG" >/dev/null 2>&1; then
          echo "Tag $TAG already exists. Skipping."
        else
          git config user.name "gitlab-ci"
          git config user.email "gitlab-ci@crusoe.ai"
          git tag "$TAG"
          git push "https://ci-push-token:${REPO_ACCESS_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git" "$TAG"
        fi
      else
        echo "VERSION file not changed. Skipping."
      fi
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
